config/routes.rb
Rails.application.routes.draw do
  # Routes for the Response resource:

  # Routes for the homepage
  get("/", {:controller => "interest_indications", :action => "index"})

  # READ
  get "/thankyou", :controller => "responses", :action => "thankyou"


  # CREATE
  get "/get_feedback/:id", :controller => "interest_indications", :action => "get_feedback"
  get "/responses/new_participated/:id", :controller => "responses", :action => "new_participated"
  get "/responses/new_dnp/:id", :controller => "responses", :action => "new_dnp"

  post "/create_response", :controller => "responses", :action => "create"

  get "/responses", :controller => "responses", :action => "index"
  get "/responses/:id", :controller => "responses", :action => "show"

  # UPDATE
  get "/responses/:id/edit", :controller => "responses", :action => "edit"
  post "/update_response/:id", :controller => "responses", :action => "update"

  # DELETE
  get "/delete_response/:id", :controller => "responses", :action => "destroy"
  #------------------------------

  # Routes for the Interest_indication resource:
  # CREATE
  get "/interest_indications/new", :controller => "interest_indications", :action => "new"
  post "/create_interest_indication", :controller => "interest_indications", :action => "create"

  # READ
  get "/interest_indications", :controller => "interest_indications", :action => "index"
  get "/interest_indications/:id", :controller => "interest_indications", :action => "show"

  # UPDATE
  get "/interest_indications/:id/edit", :controller => "interest_indications", :action => "edit"
  post "/update_interest_indication/:id", :controller => "interest_indications", :action => "update"

  get "/interest_indications/:id/remove_interest", :controller => "interest_indications", :action => "remove_interest"
  post "/remove_interest_indication/:id", :controller => "interest_indications", :action => "interest_false"

  # DELETE
  get "/delete_interest_indication/:id", :controller => "interest_indications", :action => "destroy"
  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest_indication.rb
class InterestIndication < ApplicationRecord

  has_one :interest_outcome, :class_name => "Response", :dependent => :nullify


  validates :competition_name, :presence => true
  validates :email_address, :presence => true, :uniqueness => { :scope => :competition_name }

end

app/models/response.rb
class Response < ApplicationRecord

belongs_to :interest_indication

validates :interest_indication_id, :presence => true, :uniqueness => true
validates :outcome, :presence => true
validates :likely_to_recommend, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  require 'csv'

end

app/controllers/interest_indications_controller.rb
class InterestIndicationsController < ApplicationController
  def index
    @interest_indications = InterestIndication.all
    @responses = Response.all

    render("interest_indications/index.html.erb")
  end

  def show
    @interest_indication = InterestIndication.find(params[:id])
    @responses = Response.all

    @feedback = Response.find_by( {:interest_indication_id => @interest_indication.id})

    render("interest_indications/show.html.erb")
  end

  def get_feedback
    @interest_indication = InterestIndication.find(params[:id])
    render("interest_indications/get_feedback.html.erb")

  end

  def new
    @interest_indication = InterestIndication.new

    render("interest_indications/new.html.erb")
  end

  def create
    @interest_indication = InterestIndication.new

    @interest_indication.interest = params[:interest]
    @interest_indication.competition_name = params[:competition_name]
    @interest_indication.email_address = params[:email_address]
    @interest_indication.end_date = params[:end_date]

    save_status = @interest_indication.save

    if save_status == true
      redirect_to("/interest_indications/", :notice => "Interest indication created successfully.")
    else
      render("interest_indications/new.html.erb")
    end
  end

  def edit
    @interest_indication = InterestIndication.find(params[:id])

    render("interest_indications/edit.html.erb")
  end

  def remove_interest
    @interest_indication = InterestIndication.find(params[:id])
    render("interest_indications/remove_interest.html.erb")
  end

  def update
    @interest_indication = InterestIndication.find(params[:id])

    @interest_indication.interest = params[:interest]
    @interest_indication.competition_name = params[:competition_name]
    @interest_indication.email_address = params[:email_address]
    @interest_indication.end_date = params[:end_date]

    save_status = @interest_indication.save

    if save_status == true
      redirect_to("/interest_indications", :notice => "Interest indication updated.")
    else
      render("interest_indications/edit.html.erb")
    end
  end


  def destroy
    @interest_indication = InterestIndication.find(params[:id])

    @interest_indication.destroy

    if URI(request.referer).path == "/interest_indications/#{@interest_indication.id}"
      redirect_to("/", :notice => "Interest indication deleted.")
    else
      redirect_to(:back, :notice => "Interest indication deleted.")
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

    def thank_you
      render("thankyou.html.erb")
    end

  def index
    @responses = Response.all

    respond_to do |format|
      format.html
      format.csv do
     headers['Content-Disposition'] = "attachment; filename=\"response-list.csv\""
     headers['Content-Type'] ||= 'text/csv'
       end
     end

    render("responses/index.html.erb")
  end

  def show
    @response = Response.find(params[:id])
    @outcometext = if @response.outcome == "DNP"
      "Why did you not participate in the competition even though you indicated interest in it?"
    else
      "What is the most important reason for your score?"
    end
    render("responses/show.html.erb")
  end

  def new_participated
    @interest_indication = InterestIndication.find(params[:id])
    @competition_name = InterestIndication.find(params[:id]).competition_name
    @response = Response.new

    render("responses/new_participated.html.erb")
  end

  def new_dnp
    @interest_indication = InterestIndication.find(params[:id])
    @competition_name = InterestIndication.find(params[:id]).competition_name
    @response = Response.new

    render("responses/new_dnp.html.erb")
  end


  def create
    @response = Response.new

    @response.interest_indication_id = params[:interest_indication_id]
    @response.outcome = params[:outcome]
    @response.likely_to_recommend = params[:likely_to_recommend]
    @response.do_again = params[:do_again]
    @response.improvement_suggestions = params[:improvement_suggestions]

    save_status = @response.save

    if save_status == true
      render("thankyou.html.erb", :notice => "Thank you for completing the feedback survey.")
    else
      render("responses/new.html.erb")
    end
  end

  def edit
    @response = Response.find(params[:id])

    render("responses/edit.html.erb")
  end

  def update
    @response = Response.find(params[:id])

    @response.interest_indication_id = params[:interest_indication_id]
    @response.outcome = params[:outcome]
    @response.likely_to_recommend = params[:likely_to_recommend]
    @response.do_again = params[:do_again]
    @response.improvement_suggestions = params[:improvement_suggestions]

    save_status = @response.save

    if save_status == true
      redirect_to("/responses/#{@response.id}", :notice => "Response updated successfully.")
    else
      render("responses/edit.html.erb")
    end
  end


  def destroy
    @response = Response.find(params[:id])

    @response.destroy

    if URI(request.referer).path == "/responses/#{@response.id}"
      redirect_to("/", :notice => "Response deleted.")
    else
      redirect_to(:back, :notice => "Response deleted.")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/interest_indications/edit.html.erb
<!-- Validation failure messages -->
<% if @interest_indication.errors.any? %>
  <% @interest_indication.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Interest Indication for <%= @interest_indication.competition_name %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_interest_indication/<%= @interest_indication.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for interest -->



         <div class="checkbox">
           <label for="interest" class="control-label">
           </label>

             <input type="hidden" id="interest" name="interest" value="1" <%= "checked" if @interest_indication.interest %>>
         </div>


      <!-- Label and input for competition_name -->
      <div class="form-group">
        <label for="competition_name" class="control-label">
          Competition name
        </label>

        <input type="text" id="competition_name" name="competition_name" placeholder="Competition name" class="form-control" value="<%= @interest_indication.competition_name %>">
      </div>

      <!-- Label and input for email_address -->
      <div class="form-group">
        <label for="email_address" class="control-label">
          Email address
        </label>

        <input type="text" id="email_address" name="email_address" placeholder="Email address" class="form-control" value="<%= @interest_indication.email_address %>">
      </div>

      <!-- Label and input for end_date -->
      <div class="form-group">
        <label for="end_date" class="control-label">
          End date
        </label>

        <input type="text" id="end_date" name="end_date" placeholder="End date" class="form-control" value="<%= @interest_indication.end_date %>">
      </div>

      <button class="btn btn-warning">
        Update Interest Indication
      </button>
      or
      <a href="/interest_indications/<%= @interest_indication.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/interest_indications/get_feedback.html.erb
<div class="page-header">
  <h1>Follow up Survey for Kellogg Competitions</h1>
</div>

<div class="page-header">
  <h3>You showed interest in the following competition:</h3>
  <h3><strong><%= @interest_indication.competition_name %></strong></h3>
</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <h3> Did you participate and/or enter in the competition?</h3>

    <div class="btn-lrg">
      <a href="/responses/new_participated/<%= @interest_indication.id %>" class="btn btn-success">
        Yes, I participated in the competition.
      </a>
      <a href="/responses/new_dnp/<%= @interest_indication.id %>" class="btn btn-danger">
        No, I ended up not moving forward with it.
      </a>
    </div>
  </div>
</div>

app/views/interest_indications/index.html.erb
<div class="page-header">
  <h1>
    Interest indications by competition
  </h1>
  <p>
    A table of instances where users have indicated interest in a compeition.
  </p>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Competition name</th>
        <th>Email address</th>
        <th>Interested?</th>
        <th>End date</th>
        <th>Actions</th>
        <th>Feedback (View = Complete)</th>
      </tr>

      <% @interest_indications.each do |interest_indication| %>
      <tr>
        <td><%= interest_indication.competition_name %></td>
        <td><%= interest_indication.email_address %></td>
        <td><%= interest_indication.interest %></td>
        <td><%= interest_indication.end_date %></td>
        <td>
          <a href="/interest_indications/<%= interest_indication.id %>" class="btn btn-primary">Show</a>
          <a href="/interest_indications/<%= interest_indication.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/interest_indications/<%= interest_indication.id %>/remove_interest" class="btn btn-danger">Change Interest</a>
        </td>

        <td>
          <% if interest_indication.interest == nil%>
          N/A - removed interest

          <% elsif @responses.exists?(interest_indication_id: interest_indication.id) == false%>
          <a href ="/get_feedback/<%=interest_indication.id%>" class="btn btn-success">Request Feedback</a>
        <%else%>
          <a href ="/responses/<%=Response.find_by( {:interest_indication_id => interest_indication.id}).id%>">View Feedback</a>
        <%end%>
        </td>

      </tr>
      <%end%>

    </table>
  </div>
  <a href="/interest_indications/new" class="btn btn-success">Add an interest indication to this table</a>
</div>

app/views/interest_indications/new.html.erb
<!-- Validation failure messages -->
<% if @interest_indication.errors.any? %>
  <% @interest_indication.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Add Interest Indication</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/create_interest_indication" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for interest -->
      <div class="checkbox">
          <input type="hidden" id="interest" name="interest" value="1" <%= "checked" if @interest_indication.interest %>>
      </div>


      <!-- Label and input for competition_name -->
      <div class="form-group">
        <label for="competition_name" class="control-label">
          Competition name
        </label>

        <input type="text" id="competition_name" name="competition_name" placeholder="Competition name" class="form-control" value="<%= @interest_indication.competition_name %>">
      </div>

      <!-- Label and input for email_address -->
      <div class="form-group">
        <label for="email_address" class="control-label">
          Email address
        </label>

        <input type="text" id="email_address" name="email_address" placeholder="Email address" class="form-control" value="<%= @interest_indication.email_address %>">
      </div>

      <!-- Label and input for end_date -->
      <div class="form-group">
        <label for="end_date" class="control-label">
          End date
        </label>

        <input type="text" id="end_date" name="end_date" placeholder="End date" class="form-control" value="<%= @interest_indication.end_date %>">
      </div>

      <button class="btn btn-success">
        Create Interest Indication
      </button>
      or
      <a href="/interest_indications">Cancel</a>
    </form>
  </div>
</div>

app/views/interest_indications/remove_interest.html.erb
<!-- Validation failure messages -->
<% if @interest_indication.errors.any? %>
  <% @interest_indication.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Interest Indication for <%= @interest_indication.competition_name %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_interest_indication/<%= @interest_indication.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">


      <!-- Label and input for competition_name -->
      <div class="form-group">
        <label for="competition_name" class="control-label">
        </label>
        <input type="hidden" id="competition_name" name="competition_name" placeholder="Competition name" class="form-control" value="<%= @interest_indication.competition_name %>">
      </div>

      <!-- Label and input for email_address -->
      <div class="form-group">
        <label for="email_address" class="control-label">
        </label>

        <input type="hidden" id="email_address" name="email_address" placeholder="Email address" class="form-control" value="<%= @interest_indication.email_address %>">
      </div>

      <!-- Label and input for end_date -->
      <div class="form-group">
        <label for="end_date" class="control-label">
        </label>

        <input type="hidden" id="end_date" name="end_date" placeholder="End date" class="form-control" value="<%= @interest_indication.end_date %>">
      </div>


      <!-- Label and input for interest -->

<h3>
      <div class="checkbox">
        <label for="interest">
         <input type="checkbox" id="interest" name="interest" value="1" <%= "checked" if @interest_indication.interest %>>
      Unchecked removes interest and checked indicates interest in this competition

        </label>
     </div>
</h3>
      <button class="btn btn-lrg btn-danger">
        Confirm Interest Indication
      </button>
      or
      <a href="/interest_indications/<%= @interest_indication.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/interest_indications/show.html.erb
<div class="page-header">
  <h3>Interest indicated for <%= @interest_indication.competition_name %></h3>
  <p> by <%= @interest_indication.email_address %></p>

</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <dl class="dl-horizontal">
      <dt>Feedback Status:</dt>
      <dd>
        <td>  <% if @responses.exists?(interest_indication_id: @interest_indication.id) == false%>
          <a href ="/get_feedback/<%=@interest_indication.id%>" class="btn btn-success">Request Feedback</a>
        <%else%>
          <a href ="/responses/<%=Response.find_by( {:interest_indication_id => @interest_indication.id}).id%>">View Feedback</a>
        <%end%>
        </td>
      </dd>


    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/interest_indications" class="btn btn-primary">
        Back
      </a>
      <a href="/interest_indications/<%= @interest_indication.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_interest_indication/<%= @interest_indication.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CasechampTool</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
        /* Only necessary if you are using navbar-fixed-top */
      body {
        padding-top: 60px;
        }
    </style>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  </head>


<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">Feedback Tool</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/interest_indications">Interest Indications</a></li>
          <li><a href="/responses">Feedback Responses</a></li>
          <li><a href="/rails/info">Sitemap</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="http://casechamp-staging.herokuapp.com">Return to Kellogg Competitions</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/responses/edit.html.erb
<!-- Validation failure messages -->
<% if @response.errors.any? %>
  <% @response.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Response #<%= @response.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_response/<%= @response.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for interest_indication_id -->
      <div class="form-group">
        <label for="interest_indication_id" class="control-label">
          Interest indication
        </label>

        <%= select_tag(:interest_indication_id, options_from_collection_for_select(InterestIndication.all, :id, :competition_name, @response.interest_indication_id), :class => "form-control") %>
      </div>

      <!-- Label and input for outcome -->
      <div class="form-group">
        <label for="outcome" class="control-label">
          Outcome
        </label>

        <input type="text" id="outcome" name="outcome" placeholder="Outcome" class="form-control" value="<%= @response.outcome %>">
      </div>

      <!-- Label and input for likely_to_recommend -->
      <div class="form-group">
        <label for="likely_to_recommend" class="control-label">
          How likely are you to recommend this competition to a current Kellogg student?
        </label>

        <input type="text" id="likely_to_recommend" name="likely_to_recommend" placeholder="Likely to recommend" class="form-control" value="<%= @response.likely_to_recommend %>">
      </div>

      <!-- Label and input for do_again -->
      <div class="checkbox">
        <div><strong>Would you participate in this competition again?</strong></div>
        <div>
        <label for="do_again">

          <div><input type="checkbox" id="do_again" name="do_again" value="1" <%= "checked" if @response.do_again %>> </div>
        Yes I would participate in this competition again!
      </label>
      </div>
      </div>

      <!-- Label and input for improvement_suggestions -->
      <div class="form-group">
        <label for="improvement_suggestions" class="control-label">
          Improvement suggestions
        </label>

        <textarea id="improvement_suggestions" name="improvement_suggestions" placeholder="Improvement suggestions" class="form-control" rows="3"><%= @response.improvement_suggestions %></textarea>
      </div>

      <button class="btn btn-warning">
        Update Response
      </button>
      or
      <a href="/responses/<%= @response.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/responses/index.csv.erb
<%- headers = ['Outcome', 'Likely to Recommend','Reason for Score' 'Do Again?'] -%>
<%= CSV.generate_line headers %>
<%- @responses.each do |response| -%>
<%= CSV.generate_line([response.outcome, response.likely_to_recommend, response.improvement_suggestions, response.do_again, ]) -%>
<%- end -%>

app/views/responses/index.html.erb
<div class="page-header">
  <h1>
    Responses
  </h1>
  <%= link_to 'Download CSV list', responses_path(format: :csv) %>

</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Interested in</th>
        <th>Outcome</th>
        <th>Net Promoter Score</th>
        <th>Reason for NPS</th>
        <th>Participate again?</th>
        <th>Actions</th>
      </tr>



      <% @responses.each do |response| %>
      <tr>
        <td><a href="/interest_indications/<%= response.interest_indication_id %>"><%= InterestIndication.find_by( {:id => response.interest_indication_id}).competition_name %></a></td>
        <td><%= response.outcome %></td>
        <td><%= response.likely_to_recommend %></td>
        <td><%= response.improvement_suggestions %></td>
        <td><%= response.do_again %></td>
        <td>
          <a href="/responses/<%= response.id %>" class="btn btn-primary">Show</a>
          <a href="/responses/<%= response.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_response/<%= response.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/responses/new_dnp.html.erb
<!-- Validation failure messages -->
<% if @response.errors.any? %>
  <% @response.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Share Feedback with Kellogg Competitions for <%= @competition_name %> </h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/create_response" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for improvement_suggestions -->
      <div class="form-group">
        <label for="improvement_suggestions" class="control-label">
          What prevented you from participating in the competition even though you indicated interest in it?
        </label>

        <textarea id="improvement_suggestions" name="improvement_suggestions" placeholder="Please share your reason(s) for not moving forward with the competition." class="form-control" rows="3"><%= @response.improvement_suggestions %></textarea>
      </div>

      <!-- Label and input for likely_to_recommend -->
      <div class="form-group">

        <label for="likely_to_recommend" class="control-label">
          How likely are you to recommend this competition to a current Kellogg student?
        </label>

        <!--<input type="text" id="likely_to_recommend" name="likely_to_recommend" placeholder="Likely to recommend" class="form-control" value="<%= @response.likely_to_recommend %>">
        -->
        <ul>
      <label class="radio-inline">
        <input type="radio" name="likely_to_recommend" id="likely_to_recommend" value="1"> 1
      </label>
      <label class="radio-inline">
        <input type="radio" name="likely_to_recommend" id="likely_to_recommend" value="2"> 2
      </label>
      <label class="radio-inline">
        <input type="radio" name="likely_to_recommend" id="likely_to_recommend" value="3"> 3
      </label>
      <label class="radio-inline">
        <input type="radio" name="likely_to_recommend" id="likely_to_recommend" value="4"> 4
      </label>
      <label class="radio-inline">
        <input type="radio" name="likely_to_recommend" id="likely_to_recommend" value="5"> 5
      </label>
    </div>

      <!-- Label and input for interest_indication_id -->
      <div class="form-group">
        <label for="interest_indication_id" class="control-label">
        </label>

        <input type="hidden" id="interest_indication_id" name="interest_indication_id" class="form-control" value="<%= @interest_indication.id %>">
      </div>

      <!-- Label and input for outcome -->
      <div class="form-group">
          <label for="outcome" class="control-label">
            <input type="hidden" name="outcome" id="outcome" class="form" value="DNP">
          </label>
        </div>





      <!-- Label and input for do_again -->
      <div class="checkbox">
        <label for="do_again">
          <input type="hidden" id="do_again" name="do_again" value="0" <%= "checked" if @response.do_again %>>
        </label>
      </div>



      <button class="btn btn-success">
        Submit Response
      </button>
      or
      <a href="/responses">Cancel</a>
    </form>
  </div>
</div>

app/views/responses/show.html.erb
<div class="page-header">
  <h3>Feedback response for <%= InterestIndication.find_by( {:id => @response.interest_indication_id}).competition_name %></h3>
  <p>by  <%= InterestIndication.find_by( {:id => @response.interest_indication_id}).email_address%></p>
</div>

<div class="row">
  <div class="col-md-12 mb-">
    <dl>
      <dt>The outcome of interest in and participation with this competition:</dt>
      <dd><%= @response.outcome %></dd>

      <dt>Would you partipate in this competition again?</dt>
      <dd><%= @response.do_again %></dd>

</dl>
<dl>

      <dt>How likely are you to recommend this competition to a current Kellogg student?</dt>
      <dd><%= @response.likely_to_recommend %> / 5 </dd>


      <dt><%=@outcometext%></dt>
      <dd> <%=@response.improvement_suggestions %> </dd>
    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/responses" class="btn btn-primary">
        Back
      </a>
      <a href="/responses/<%= @response.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_response/<%= @response.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>

app/views/responses/thankyou.html.erb
<div class="page-header">
  <h3>Thank you!</h3>
</div>

<div class="row">
  <div class="col-md-12 mb-2">
    <p>Thank you for completing the follow up survey based on your interest in competitions at Kellogg.</p>
  </div>
  <a href="http://casechamp-staging.herokuapp.com/" class="btn btn-success">Return to Kellogg Competitions</a>
</div>
  </div>
</div>